apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ticketing-web-hpa
  namespace: ticketing-web
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ticketing-web-deployment
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50  # 50%로 낮춤 (기존 70%)
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 30  # 스케일 업 대기 시간 감소
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
