name: fe CI

on:
  push:
    branches: ['main']
    # paths-ignore: ['.github/**']

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure AWS credentials for ECR
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_URI: 206177862976.dkr.ecr.ap-northeast-2.amazonaws.com/ticketing/web
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build --platform=linux/amd64 -t $ECR_URI:$IMAGE_TAG .
          docker push $ECR_URI:$IMAGE_TAG
      
      - name: Trigger ticketing-ops repo
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT }}
          repository: ssg-project/ticketing-ops
          event-type: update-image
          client-payload: '{"sha": "${{ github.sha }}", "repo": "fe"}'
